### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/opuscoords#2]
This looks like another functionality that has been replaced by Astropy coordinates package?

**Comment by embray** [comment]
I certainly haven't noticed activity on opuscoords in a long time.  Would be interesting to see where it's used and if/how Astropy can be substituted.

**Comment by jhunkeler** [comment]
As far as I know, nothing depends on this package. Apparently the pipeline has used this in previous builds but I have no idea if they still require it.

**Comment by SaOgaz** [comment]
Got the go ahead from @stsci-hack to archive this repo!
